services:
  postgres:
    image: bitnami/postgresql:16
    ports:
      - '5482:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orbit
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - postgresql_data:/bitnami/postgresql

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP

  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - "3333:3333"
  frontend:
    build:
      context: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgresql_data:
